build-job:
  script: echo "This is a placeholder script"

  stages:
    - backend_build
    - frontend_build
    - test
    - deploy

  before_script:
    - apt-get update -qy
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs
    - npm install -g @angular/cli@12.0.5
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - rm composer-setup.php

  backend_install_dependencies:
    stage: backend_build
    script:
      - cd back
      - composer install

  frontend_install_dependencies:
    stage: frontend_build
    script:
      - cd front
      - npm install

  frontend_build:
    stage: frontend_build
    script:
      - cd front
      - ng build --prod

  test:
    stage: test
    script:
      # Ajoutez ici vos commandes de tests si nécessaire

  deploy:
    stage: deploy
    only:
      - master
    script:
      # Ajoutez ici vos commandes de déploiement si nécessaire
